name = "DependencyWalker"
uuid = "7db386b5-e858-4964-8eb4-2fa66f8df882"
authors = ["Mos√® Giordano"]
version = "0.1.0"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
ObjectFile = "d8793406-e978-5875-9003-1fc021f44a92"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
Crayons = "4.0.1"
ObjectFile = "0.3"
julia = "1.3"

[extras]
SymEngine_jll = "3428059b-622b-5399-b16f-d347a77089a4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SymEngine_jll", "Test"]
